version: '3.8'
services:
  backend:
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  frontend:
    build: ./tictactoe_front
    ports:
      - "3000:3000"
    volumes:
      - ./tictactoe_front:/usr/src/app
    depends_on:
      - backend
